DEV: remove bundle cache
discourse/discourse_docker pull request #852
Opened 2024-08-30 02:03 UTC by featheredtoast

On the current image this removes ~78MB from the layer

2024-08-30 02:06 UTC, tgxworld approved these changes

2024-08-30 02:21 UTC, tgxworld requested changes
Looks like the build is not happy 🤔

2024-08-30 18:20 UTC, featheredtoast commented
aw phoo, seems like this is required to keep then

2024-08-30 23:44 UTC, featheredtoast commented
I've updated the find + delete, looks like there's a cache folder within */gems/* as well -- added to the ignore list on the find command. 👍

2024-08-31 00:58 UTC, tgxworld approved these changes

2024-08-31 01:05 UTC, merged